### ISSUE TITLE
[Error] Exception: System.InvalidOperationException (Log)

### ISSUE THREAD

**Issue by whateverpop** [Ar1i/PokemonGo-Bot#1036]
[01:10:52] _____________________________
[01:10:52] Exception: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPokemonToEvolve>d__14.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Inventory.cs:line 127
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<EvolveAllPokemonWithEnoughCandy>d__19.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 576
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__11.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 138
[01:10:52] Starting again.. But waiting 10 Seconds..

**Comment by Smux** [comment]
also have this problem. in another issue thread someone said its due to pokemon go server issues

**Comment by FrancYescO** [comment]
https://github.com/Ar1i/PokemonGo-Bot/issues/1033

**Comment by elenex23** [comment]
It normally fixes itself. If not restarting the bot should fix.

**Comment by xJustx** [comment]
^
