### ISSUE TITLE
InvalidResponseException

### ISSUE THREAD

**Issue by vsoraas** [Ar1i/PokemonGo-Bot#115]
```
[23:11:19] Starting again.. But waiting 10 Seconds..  
[23:11:59] [#0 of 25] retry request https://pgorelease.nianticlabs.com/plfe/rpc
- Error: System.Exception: Exception of type 'System.Exception' was thrown.
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext()  
[23:12:02] _____________________________  
[23:12:02] Level: 24  
[23:12:02] EXP Needed: 150000  
[23:12:02] Current EXP: 11025 (7%)  
[23:12:02] EXP to Level up: 138975  
[23:12:02] KM Walked: 108.9382  
[23:12:02] PokeStops visited: 3547  
[23:12:02] Stardust: 164352  
[23:12:02] Pokemon to evolve: 53  
[23:12:02] _____________________________  
[23:12:03] We found 220 PokeStops near.  
[23:12:03] Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: E
xception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was t
hrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0
`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetMapObjects>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteCatchAllNearbyPokemons>d__13.MoveN
ext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__12.
MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__8.MoveNext()
[23:12:03] Starting again.. But waiting 10 Seconds..
[23:12:43] [#0 of 25] retry request https://pgorelease.nianticlabs.com/plfe/rpc
- Error: System.Exception: Exception of type 'System.Exception' was thrown.
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext()

```

**Comment by vsoraas** [comment]
```
[23:15:11] Starting again.. But waiting 10 Seconds..
[23:15:23] _____________________________
[23:15:23] Level: 24
[23:15:23] EXP Needed: 150000
[23:15:23] Current EXP: 11025 (7%)
[23:15:23] EXP to Level up: 138975
[23:15:23] KM Walked: 109.0827
[23:15:23] PokeStops visited: 3547
[23:15:23] Stardust: 164352
[23:15:23] Pokemon to evolve: 53
[23:15:23] _____________________________
[23:15:24] We found 224 PokeStops near.
[23:15:24] Found 3 catchable Pokemon(s).
[23:15:24] Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: E
xception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was t
hrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0
`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<StatsLog>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteCatchAllNearbyPokemons>d__13.MoveN
ext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__12.
MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__8.MoveNext()
[23:15:24] Starting again.. But waiting 10 Seconds..

```

**Comment by Sparco2313** [comment]
Having the same issue

**Comment by Deske043** [comment]
Same..

**Comment by Ar1i** [comment]
Server is lagging. Wtf guys how many thinks you want to open. Read on the Forum.
