### ISSUE TITLE
Issue Please help

### ISSUE THREAD

**Issue by Zekov** [Ar1i/PokemonGo-Bot#1423]
I fully understand that the pokestops arnt working but its not the pokestops for me everytime I open it and run bot it keeps saying 
PokemonGo.RocketAPI.Exceptions.GoogleException: BadAuthentication
   at PokemonGo.RocketAPI.Login.GoogleLoginGPSOAuth.DoLogin(String username, String password) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Login\GoogleLoginGPSOAuth.cs:line 34
   at PokemonGo.RocketAPI.Client.<DoGoogleLogin>d__25.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Client.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 53 

Prev I deleted it because I wanted to bot another account but it kept saving my prev cords so I deleted the file still nothing then i redownloaded the newest version and says the above 

If Ar1i is reading this good work and keep up your hard work.

**Comment by Biscuit090** [comment]
This means you typed a wrong password or username. See line 1 it says "BadAuthentication...(String username, String password)? Try a different password or maybe your combination of usernames and passwords is wrong.
