### ISSUE TITLE
No matching element

### ISSUE THREAD

**Issue by shahroozal** [Ar1i/PokemonGo-Bot#1492]
So this error keeps coming up.

```
[15:51:49] Exception: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at PokemonGo.RocketAPI.Rpc.Inventory.<GetPokemonToEvolve>d__2.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Rpc\Inventory.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<StatsLog>d__13.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteCatchAllNearbyPokemons>d__17.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:line 479
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Navigation.<HumanLikeWalking>d__4.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Navigation.cs:line 88
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__16.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:line 375
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:line 124
```

**Comment by pokerave** [comment]
![damn](https://cloud.githubusercontent.com/assets/20603254/17462772/4437a548-5cc0-11e6-9542-247d76c2b64e.png)

**Comment by shahroozal** [comment]
@pokerave yea I saw that on twitter but it was too late :D
