### ISSUE TITLE
This Error?

### ISSUE THREAD

**Issue by Tochez** [Ar1i/PokemonGo-Bot#150]
[22:14:07] Error: Pokemon Go Rocket API
[22:14:07] PokemonGo.RocketAPI.Exceptions.GoogleException: BadAuthentication
   at PokemonGo.RocketAPI.Login.GoogleLoginGPSOAuth.DoLogin(String username, String password) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Login\GoogleLoginGPSOAuth.cs:line 34
   at PokemonGo.RocketAPI.Client.<DoGoogleLogin>d__25.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Client.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__8.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 50

**Comment by Ar1i** [comment]
Your Login Data is wrong!

**Comment by Tochez** [comment]
oh ok!

**Comment by Tochez** [comment]
thanks
