### ISSUE TITLE
 Invalid URI: The hostname could not be parsed.

### ISSUE THREAD

**Issue by lamweixing** [Ar1i/PokemonGo-Bot#1553]
[16:37:15] Exception: System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at System.Net.Http.HttpClient.CreateUri(String uri)
   at System.Net.Http.HttpClient.PostAsync(String requestUri, HttpContent content)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__6`2.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__3.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Rpc\Player.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:line 109

**Comment by Logxn** [comment]
Wierd. Do you get that spammed or only once?

**Comment by DeemonRider** [comment]
yes, starting again in 10 seconds and again this error.
