### ISSUE TITLE
Any ideas on how to fix this ?

### ISSUE THREAD

**Issue by eden764** [Ar1i/PokemonGo-Bot#1608]
so... I created an account (google) 1 hour ago, level him up to level 3 (manually) and then I attempted to use the new bot.
from some reason when I start the bot im getting alot of error messages and im not sure why... any ideas ?

log : 

[18:44:26] Starting Execute on login server: Google
[18:44:27] Error reloading Pokemon list: BadAuthentication
[18:44:27] Error: Pokemon.Go.Rocket.API
[18:44:27] PokemonGo.RocketAPI.Exceptions.GoogleException: BadAuthentication
   at PokemonGo.RocketAPI.Login.GoogleLogin.<GetAccessToken>d__3.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Rpc\Login.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__9.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:line 58
[18:44:27] Trying to Restart.
[18:44:27] Restarting in 10 Seconds.
[18:44:28] Error reloading Pokemon list: BadAuthentication
[18:44:29] Error reloading Pokemon list: BadAuthentication

**Comment by PokePro21** [comment]
just change the location and try

**Comment by sunit1998** [comment]
check ur acc id and password its wrong so ur getting error

**Comment by arjunvegda** [comment]
Also try changing the password.

you can see the errors I faced here #1573

**Comment by xJustx** [comment]
^
