### ISSUE TITLE
Version 1.0 is crashing constantly

### ISSUE THREAD

**Issue by kxngrocafella** [Ar1i/PokemonGo-Bot#166]
Here is the error... it tries to restart then loops over again. Also seems to be pointing to something on Ari's local PC.

[15:25:36] Error: Pokemon Go Rocket API
[15:25:36] PokemonGo.RocketAPI.Exceptions.GoogleException: BadAuthentication
   at PokemonGo.RocketAPI.Login.GoogleLoginGPSOAuth.DoLogin(String username, String password) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Login\GoogleLoginGPSOAuth.cs:line 34
   at PokemonGo.RocketAPI.Client.<DoGoogleLogin>d__25.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Client.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__8.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 50

**Comment by andrekkn** [comment]
did you try the obvious? username/password combo is wrong

**Comment by kxngrocafella** [comment]
The error is not with my username and password...

If you read the error it says error in "C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo"

**Comment by Ar1i** [comment]
Your login Data is wrong.
