### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by OhhPian** [Ar1i/PokemonGo-Bot#1688]
Anyone know what is this error ? 
![error](https://cloud.githubusercontent.com/assets/17487706/17464385/95c4363e-5d0f-11e6-8b7a-75c5449f9ce0.PNG)

**Comment by Jacowork** [comment]
Same with me

[20:27:52] Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at PokemonGo.RocketAPI.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Utils\LocationUtils.cs:line 23
   at PokemonGo.RocketAPI.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double bearingDegrees) in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Utils\LocationUtils.cs:line 64
   at PokemonGo.RocketAPI.Logic.Navigation.<HumanLikeWalking>d__4.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Navigation.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__17.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:line 395
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:line 129

**Comment by Ar1i** [comment]
should be fixed

**Comment by gahget** [comment]
api chanced again? same here :(

**Comment by gahget** [comment]
It was working ten minutes ago.

**Comment by OhhPian** [comment]
Restart and it happen again.

[02:31:27] Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at PokemonGo.RocketAPI.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Utils\LocationUtils.cs:line 23
   at PokemonGo.RocketAPI.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double bearingDegrees) in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Utils\LocationUtils.cs:line 64
   at PokemonGo.RocketAPI.Logic.Navigation.<HumanLikeWalking>d__4.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Navigation.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__17.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:line 395
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:line 129
[02:31:27] Starting again in 10 seconds...

**Comment by Jacowork** [comment]
Update the app, it works fine now!!!

**Comment by OhhPian** [comment]
It works ! Thanks ^^
