### ISSUE TITLE
Bot not working anymore

### ISSUE THREAD

**Issue by Nolera** [Ar1i/PokemonGo-Bot#2047]
it say theres no pokestop around you.
sorry for my bad english...

**Comment by roooochi** [comment]
restart it lol

**Comment by louzifer** [comment]
restart it is not working

**Comment by artasakha** [comment]
try to restart your router and just running one account at the time. works for me

**Comment by Nolera** [comment]
ooh yes it works... thanks you guys

**Comment by akangnduz** [comment]
soft banned IP detected...
- wait 5-10 minute or 
- use vpn to resolve this issue or
- restart router

**Comment by louzifer** [comment]
i have a static ip

**Comment by akangnduz** [comment]
use vpn then

**Comment by louzifer** [comment]
maybe an vpn add for the bot, so u can choose it directly

**Comment by navygino** [comment]
Latest Build - 07.08 15.48 is working but Latest Build - 08.08 08.14 is not working and has the below msg....
[23:37:07] We found 205 PokeStops near your current location.
[23:37:08] Next Pokestop: General Sherman Sculpture in 12.42m distance.
[23:37:08] Distance to target location: 12.42 meters. Will take 0.56 seconds!
[23:37:29] Exception: System.Net.WebException: Unable to connect to the remote s
erver ---> System.Net.Sockets.SocketException: A connection attempt failed becau
se the connected party did not properly respond after a period of time, or estab
lished connection failed because connected host has failed to respond 216.58.221
.234:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddre
ss socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Sock
et s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state,
IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at PokemonGo.RocketAPI.Logic.Utils.LocationUtils.getAltidude(Double lat, Doub
le lon) in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewA
PI\PokemonGo.RocketAPI.Logic\Utils\LocationUtils.cs:line 19
   at PokemonGo.RocketAPI.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate
 sourceLocation, Double distanceInMeters, Double bearingDegrees) in C:\Users\Ari
\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.
Logic\Utils\LocationUtils.cs:line 77
   at PokemonGo.RocketAPI.Logic.Navigation.<HumanLikeWalking>d__4.MoveNext() in
C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonG
o.RocketAPI.Logic\Navigation.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__17.
MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-N
ewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:line 402
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\U
sers\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.Ro
cketAPI.Logic\Logic.cs:line 129
[23:37:29] Starting again in 10 seconds...

**Comment by dadaxd** [comment]
i have the same problem

**Comment by eliteknight** [comment]
go too new town...
