### ISSUE TITLE
FIX HERE!!!

### ISSUE THREAD

**Issue by joelx3** [Ar1i/PokemonGo-Bot#2107]
Hello if you  have a Problem after the Update delete everything from the bot even the Config!

Download the new Build and Extract it.. now run the Exe as Admin.

The old CFG is corrupted.

**Comment by xJihadx** [comment]
Not working after update.

[14:40:06] Export Player Infos and all Pokemons to CSV not possible. File seems be in use!
[14:40:08] -----------------------[PLAYER STATS UPDATE]-----------------------
[14:40:08] Level/EXP: 31 139,405/500,000 (27.88%) EXP to Level up: 360595
[14:40:08] PokeStops visited: 12139 KM Walked: 126.3119
[14:40:09] Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PokemonGo.RocketAPI.Rpc.Inventory.<GetEggs>d__6.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Rpc\Inventory.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Inventory.<GetEggsCount>d__5.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Rpc\Inventory.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<StatsLog>d__14.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:line 188
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:line 115
[14:40:09] Starting again in 10 seconds...

**Comment by PureSkill** [comment]
Doesn´t work for me :(

**Comment by kalcheat** [comment]
Got the same error.

**Comment by joelx3** [comment]
Are you sure you are deleting everything and you are also starting it as Admin?

**Comment by Maxpowder** [comment]
sam here

**Comment by CreativiTimothy** [comment]
Downloaded new build and running as admin -- not working

**Comment by patrayat5505** [comment]
the error exception is random..... sometimes it works sometimes error exception..

**Comment by Zuldar** [comment]
the same for me, new folder, new config , same problem

**Comment by iZ4iN** [comment]
https://i.gyazo.com/5df1680c1e74042d7e3757ab08ee15d6.png

**Comment by freetogameplay** [comment]
work for me, just used auto transfer and auto evolve :D ![9](https://cloud.githubusercontent.com/assets/11550302/17491579/673d7744-5dd2-11e6-9de7-8fcaf0d66043.png)

**Comment by adeputu** [comment]
Doesn't work

**Comment by DiTechRacer** [comment]
Nope, does not work

**Comment by py4989** [comment]
Mines working fine it was not working earlier all i did was Replacing the New files with the Old Files yesturdays Update with todays update like only a couple files and its working fine now

**Comment by joelx3** [comment]
look working for me: http://prntscr.com/c375il

**Comment by Astifleure** [comment]
its Google server auth i think ^^

**Comment by arjunvegda** [comment]
@freetogameplay This does not seem to be Ar1i's bot. He does not have RUNTIME and next level in features.

**Comment by BluCone** [comment]
works for me

**Comment by xhalfbakedguy** [comment]
the new version isnt working and the olter 1.0.7.1 i still had doesnt work either so i dont think its a problem with the bot..

**Comment by favtim96** [comment]
Deletes all files that you have it, even the trashed , the Exe schliest in Task Manger . and upload it down again and executes it as an admin .

**Comment by freetogameplay** [comment]
@arjunvegda bot gui is left man

**Comment by jeremie152** [comment]
no worry just wait new update or log on with ptc and work again^^

**Comment by arjunvegda** [comment]
Guys its Servers I believe

http://www.mmoserverstatus.com/pokemon_go

**Comment by justchil** [comment]
Seems random probably servers.

**Comment by yasin939** [comment]
Run the program as an administrator .

**Comment by freetogameplay** [comment]
i still appreciate ar1i bot, i think it will be good bot ever

**Comment by PxrnHub** [comment]
oh and some **people** dont click the right **login type** so try that

**Comment by arjunvegda** [comment]
@freetogameplay My bad bro

**Comment by akangnduz** [comment]
delete your Configs FOLDER then start setting again it WORK!!!!

**Comment by freetogameplay** [comment]
@arjunvegda nope man

**Comment by freetogameplay** [comment]
@akangnduz lol

**Comment by Zuldar** [comment]
this one doest not work, the last is working (i test with new one folder , new one configuration for each)

**Comment by Ar1i** [comment]
#2110
