### ISSUE TITLE
RUN .EXE AS ADMIN

### ISSUE THREAD

**Issue by GHANT** [Ar1i/PokemonGo-Bot#2119]
[15:11:31] Export Player Infos and all Pokemon to "\Config\PokemonList.csv"
[15:11:32] Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PokemonGo.RocketAPI.Rpc.Inventory.<GetPlayerStats>d__24.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Rpc\Inventory.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<StatsLog>d__14.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:line 115
[15:11:32] Starting again in 10 seconds...

____

Running as an admin seems to work for now.

**Comment by lionellex** [comment]
tried, 1st account is fine. but once starting the 2nd acc this error pops out.

**Comment by GHANT** [comment]
Why are you using 2 accounts?

**Comment by lionellex** [comment]
helping a fren do it as well, but it seems to work now. thanks btw.

**Comment by GHANT** [comment]
Sure thing

**Comment by BlackHatching** [comment]
dont tick auto incubate eggs n test it

**Comment by xJustx** [comment]
^
