### ISSUE TITLE
SOLVED Error reloading Pokemon list: Exception of type 

### ISSUE THREAD

**Issue by soulbanes** [Ar1i/PokemonGo-Bot#2209]
[10:17:26] Trying to Restart.
[10:17:26] Restarting in 10 Seconds.
[10:17:27] Error reloading Pokemon list: Exception of type 'PokemonGo.RocketAPI.Exceptions.LoginFailedException' was thrown.
[10:17:28] Error reloading Pokemon list: Exception of type 'PokemonGo.RocketAPI.Exceptions.LoginFailedException' was thrown.
[10:17:29] Error reloading Pokemon list: Exception of type 'PokemonGo.RocketAPI.Exceptions.LoginFailedException' was thrown.
[10:17:30] Error reloading Pokemon list: Exception of type 'PokemonGo.RocketAPI.Exceptions.LoginFailedException' was thrown.
[10:17:31] Error reloading Pokemon list: Exception of type 'PokemonGo.RocketAPI.Exceptions.LoginFailedException' was thrown.
[10:17:33] Error reloading Pokemon list: Exception of type 'PokemonGo.RocketAPI.Exceptions.LoginFailedException' was thrown.
[10:17:34] Error reloading Pokemon list: Exception of type 'PokemonGo.RocketAPI.Exceptions.LoginFailedException' was thrown.
[10:17:35] Error reloading Pokemon list: Exception of type 'PokemonGo.RocketAPI.Exceptions.LoginFailedException' was thrown.
[10:17:36] Error reloading Pokemon list: Exception of type 'PokemonGo.RocketAPI.Exceptions.LoginFailedException' was thrown.
[10:17:37] Error: Pokemon.Go.Rocket.API
[10:17:37] PokemonGo.RocketAPI.Exceptions.LoginFailedException: Exception of type 'PokemonGo.RocketAPI.Exceptions.LoginFailedException' was thrown.
   at PokemonGo.RocketAPI.Login.PtcLogin.ExtracktTicketFromResponse(HttpResponseMessage loginResp) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 46
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetLoginTicket>d__7.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__3.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\Login.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__9.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 62
[10:17:37] Trying to Restart.

**Comment by navygino** [comment]
[10:31:54] Starting Execute on login server: Ptc
[10:31:58] Error reloading Pokemon list: Sequence contains no matching element
[10:31:59] Exception: System.NullReferenceException: Object reference not set to
 an instance of an object.
   at PokemonGo.RocketAPI.Rpc.Inventory.<GetPokemonFamilies>d__36.MoveNext() in
C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\
Inventory.cs:line 383
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Inventory.<GetPokemonToEvolve>d__2.MoveNext() in C
:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\I
nventory.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<StatsLog>d__14.MoveNext() in C:\Users\Ari
\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:l
ine 181
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\U
sers\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Lo
gic.cs:line 115
[10:31:59] Starting again in 10 seconds...
[10:32:02] Error reloading Pokemon list: Object reference not set to an instance
 of an object.
[10:32:05] Error reloading Pokemon list: Object reference not set to an instance
 of an object.
[10:32:10] Export Player Infos and all Pokemons to CSV not possible. File seems
be in use!
[10:32:12] Error reloading Pokemon list: Object reference not set to an instance
 of an object.
[10:32:13] Exception: System.NullReferenceException: Object reference not set to
 an instance of an object.
   at PokemonGo.RocketAPI.Rpc.Inventory.<GetPokemonFamilies>d__36.MoveNext() in
C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\
Inventory.cs:line 383
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Inventory.<GetPokemonToEvolve>d__2.MoveNext() in C
:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\I
nventory.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<StatsLog>d__14.MoveNext() in C:\Users\Ari
\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:l
ine 181
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\U
sers\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Lo
gic.cs:line 115
[10:32:13] Starting again in 10 seconds...
[10:32:15] Error reloading Pokemon list: Object reference not set to an instance
 of an object.
[10:32:22] Error reloading Pokemon list: Object reference not set to an instance
 of an object.
[10:32:24] Export Player Infos and all Pokemons to CSV not possible. File seems
be in use!
[10:32:27] Exception: System.NullReferenceException: Object reference not set to
 an instance of an object.
   at PokemonGo.RocketAPI.Rpc.Inventory.<GetPokemonFamilies>d__36.MoveNext() in
C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\
Inventory.cs:line 383
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Inventory.<GetPokemonToEvolve>d__2.MoveNext() in C
:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\I
nventory.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<StatsLog>d__14.MoveNext() in C:\Users\Ari
\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:l
ine 181
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\U
sers\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Lo
gic.cs:line 115
[10:32:27] Starting again in 10 seconds...
[10:32:30] Error reloading Pokemon list: Object reference not set to an instance
 of an object.
