### ISSUE TITLE
please give time here & do read all : As per video i started from begining to catch & catch pikaju as started .. & then i try to add that account to bot 

### ISSUE THREAD

**Issue by destiny2jannat** [Ar1i/PokemonGo-Bot#243]
As per video i started from begining to catch & catch pikaju as started .. & then i try to add that account to bot 

[22:47:33] Trying to Restart.
[22:47:33] Restarting in 10 Seconds.
[22:47:44] Error: Pokemon Go Rocket API
[22:47:45] PokemonGo.RocketAPI.Exceptions.GoogleException: BadAuthentication
   at PokemonGo.RocketAPI.Login.GoogleLoginGPSOAuth.DoLogin(String username, String password) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Login\GoogleLoginGPSOAuth.cs:line 34
   at PokemonGo.RocketAPI.Client.<DoGoogleLogin>d__25.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Client.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__8.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 50 

please help

**Comment by Oguzcan13** [comment]
Your password is incorrect

**Comment by 13XxM1CHA3lxX37** [comment]
Look at the output
PokemonGo.RocketAPI.Exceptions.GoogleException: **BadAuthentication**
user/email/pass is wrong

**Comment by destiny2jannat** [comment]
Thanks. . Oops my mistake & couldn't figure it out ... thanks

**Comment by baeckstrom** [comment]
@destiny2jannat please close this issue as resolved if everything worked out.
