### ISSUE TITLE
Several errors occur while loading pokemon.

### ISSUE THREAD

**Issue by jj1232727** [Ar1i/PokemonGo-Bot#2490]
![errors](https://cloud.githubusercontent.com/assets/20945561/17548525/47aadff0-5eba-11e6-9f15-c6ed2d4332e0.png)

----------------------------------------------------------------------------------------------------------------
[05:18:43] Error reloading Pokemon list: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
[05:18:45] Error reloading Pokemon list: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
[05:19:15] This bot is absolutely free and open-source!
[05:19:15] If you've paid for it. Request a chargeback immediately!
[05:19:15] Starting Execute on login server: Ptc
[05:19:18] Error reloading Pokemon list: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
[05:19:18] Error: Google.Protobuf
[05:19:18] Google.Protobuf.InvalidProtocolBufferException: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
   at Google.Protobuf.CodedInputStream.SkipLastField()
   at POGOProtos.Networking.Envelopes.ResponseEnvelope.MergeFrom(CodedInputStream input) in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\POGOProtos\Networking\Envelopes\ResponseEnvelope.cs:line 283
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__14`1.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\Login.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\Login.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__9.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 62
[05:19:18] Trying to Restart.
[05:19:18] Restarting in 10 Seconds.
[05:19:19] Error reloading Pokemon list: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
[05:19:21] Error reloading Pokemon list: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
[05:19:23] Error reloading Pokemon list: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
[05:19:25] Error reloading Pokemon list: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
[05:19:27] Error reloading Pokemon list: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
[05:19:28] Error reloading Pokemon list: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
[05:19:29] Error: Google.Protobuf
[05:19:29] Google.Protobuf.InvalidProtocolBufferException: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
   at Google.Protobuf.CodedInputStream.SkipLastField()
   at POGOProtos.Networking.Envelopes.ResponseEnvelope.MergeFrom(CodedInputStream input) in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\POGOProtos\Networking\Envelopes\ResponseEnvelope.cs:line 283
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__14`1.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\Login.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\Login.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__9.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 62
[05:19:29] Trying to Restart.
[05:19:29] Restarting in 10 Seconds.
-----------------------------------------------------------------------------------------------------------------

Attempts:
Tried several accounts. (Failed)
Tried logging in manually (Worked)
Changed gps location (Failed)
Used a vpn (Failed)
Used both a PTC and google account (Failed)
Restarted my router (Failed)
Played with the settings and gui (Failed)
Deleted the whole file and reinstalled (Failed)

This occurred in the middle of my bot running and left me with the message that no pokestops were in the area. Then I restarted and these errors happened.

Unsure if it is the servers or the bot. Hopefully it is just the servers.

**Comment by janusmiranda** [comment]
verify ur account in ur EMAIL.

**Comment by jj1232727** [comment]
Verify a google account i've had for almost 7 years now?
Also all my ptc accounts are verified. Highly doubt that is the issue

**Comment by jj1232727** [comment]
You can close the issue I figured it out. VPN issue caused authentication with both ptc and google servers
