### ISSUE TITLE
Proxy Authenticate

### ISSUE THREAD

**Issue by w19ten** [Ar1i/PokemonGo-Bot#2820]
Describe your problem!

Entered the correct proxy IP and credential:
1st it stated 403 
update the credential again, 
it state required login credential.

<
[11:16:17] Error: mscorlib
[11:16:17] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
>
<
[11:14:37] Error: mscorlib
[11:14:37] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 130.211.14.80:443
>
<
[11:03:31] Error: mscorlib
[11:03:31] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
>

Confirm its the correct credential

in VPN network environment already.

Using HTTP proxy instead HTTPS (suspect is the root cause)

**Comment by xJustx** [comment]
You have to use a HTTPS Proxy.
It's because the connection to the Niantic API requires a HTTPS connection!
So try it please with a HTTPS Proxy.
