### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by NWExKraken** [Ar1i/PokemonGo-Bot#305]
So every time he updates it should i use the build only folder or what im not exactly sure what and how this is suppose to look like anymore i had it working before now im just confused

**Comment by Playhard89** [comment]
Using only built is fine I guess ?  There is no change

**Comment by NWExKraken** [comment]
i get this now [19:10:46] [#0 of 25] retry request https://pgorelease.nianticlabs.com/plfe/rpc - Error: System.Exception: Exception of type 'System.Exception' was thrown.
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Helpers\RetryHandler.cs:line 31

**Comment by Playhard89** [comment]
Im using the build aswell, can you try to install it again ?

**Comment by NWExKraken** [comment]
sure give me a second

**Comment by NWExKraken** [comment]
[#0 of 25] retry request https://pgorelease.nianticlabs.com/plfe/rpc - Error: System.Exception: Exception of type 'System.Exception' was thrown.
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Helpers\RetryHandler.cs:line 31
