### ISSUE TITLE
Help !

### ISSUE THREAD

**Issue by Polarbear008** [Ar1i/PokemonGo-Bot#3068]
How to fix "failed  to get game data from the server " ? Please help

**Comment by gummyruler** [comment]
Try this:
https://www.youtube.com/watch?v=f-OzQQrtRQs

PGo server is out. PTC and Gmail.

**Comment by Polarbear008** [comment]
I try this but still same

**Comment by Polarbear008** [comment]
I login with ptc it work but with id gmail cant login the message while im loading "failed to get game data from the server"

**Comment by james741** [comment]
#3069

**Comment by bombomsword** [comment]
me to: 
[14:34:58] Starting Execute on login server: Google
[14:35:00] Exception: System.NullReferenceException: Object reference not set to
 an instance of an object.
   at PokemonGo.RocketAPI.Rpc.Inventory.<GetPlayerStats>d__24.MoveNext() in C:\U
sers\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\Inve
ntory.cs:line 280
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.Rpc.Inventory.<ExportPokemonToCSV>d__41.MoveNext() in
C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\
Inventory.cs:line 514
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\U
sers\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Lo
gic.cs:line 124
