### ISSUE TITLE
Boolean method not found

### ISSUE THREAD

**Issue by yeseisin** [Ar1i/PokemonGo-Bot#3319]
I got this issue, kindly advise...
Thanks..!!

************** Exception Text **************
System.MissingMethodException: Method not found: 'Boolean System.Net.Http.Headers.HttpHeaders.TryAddWithoutValidation(System.String, System.String)'.
   at PokemonGo.RocketAPI.HttpClient.PokemonHttpClient..ctor()
   at PokemonGo.RocketAPI.Client..ctor(ISettings settings) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Client.cs:line 58
   at PokemonGo.RocketAPI.Console.Pokemons.<Execute>d__9.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Console\Pokemons.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)

**Comment by yeseisin** [comment]
![image](https://cloud.githubusercontent.com/assets/21002900/17641287/689794cc-614b-11e6-89c2-567b347186dc.png)

**Comment by yeseisin** [comment]
![image](https://cloud.githubusercontent.com/assets/21002900/17641289/7a278f9e-614b-11e6-9ba2-2f0d3ecc6320.png)

**Comment by Microrock** [comment]
I just backup PokemonGo-Bot-master forder everytime after config setting.

When i got this problem same you. I copy and repaste my backup to restore.

It's OK for me.
