### ISSUE TITLE
Error Pokemon.Go.RocketAPI

### ISSUE THREAD

**Issue by k0ut4li4n0s** [Ar1i/PokemonGo-Bot#3368]
--------------------------------------------------------------------------
Error: Pokemon.Go.Rocket.API
[11:32:21] PokemonGo.RocketAPI.Exceptions.LoginFailedException: Exception of type 'PokemonGo.RocketAPI.Exceptions.LoginFailedException' was thrown.
   at PokemonGo.RocketAPI.Login.PtcLogin.ExtractTicketFromResponse(HttpResponseMessage loginResp) in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 53
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetLoginTicket>d__8.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__4.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Rpc\Login.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__9.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:line 82
---------------------------------------------------------

What is the fix for this ? 

Thanks for everything

**Comment by Logxn** [comment]
There is a problem with your Location you set.

**Comment by k0ut4li4n0s** [comment]
What about the location ? With the older version i was on the same location and didnt get this message any time. I login with the emulator to be in the same location for probable fix , even chaged the location , but still got the same error 
-------------------------------------------------------------

 Error: Pokemon.Go.Rocket.API
[13:13:10] PokemonGo.RocketAPI.Exceptions.LoginFailedException: Exception of type 'PokemonGo.RocketAPI.Exceptions.LoginFailedException' was thrown.
   at PokemonGo.RocketAPI.Login.PtcLogin.ExtractTicketFromResponse(HttpResponseMessage loginResp) in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 53
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetLoginTicket>d__8.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__4.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI\Rpc\Login.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__9.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:line 82

----------------------------------------------------------

**Comment by k0ut4li4n0s** [comment]
Nevermind set this one on sold,i made a mistake. 

What about this one is it mentioned in any other issues? 

----------------------------------------------

{ "fortId": "3125c37826ca4c63a43ebf4db8b74461.16", "name": "Cable Car", "imageUrls": [ "http://lh6.ggpht.com/MLX6o2pxCwaB2GjcCKmgm7Tbb_PVc2cs4GLi_kOD0ZuCyKXsFomtsOAd5Dhha3lsPhgqpOREZiiZJcB96fyQ" ], "type": "CHECKPOINT", "latitude": 37.809642, "longitude": -122.410227, "modifiers": [ { "itemId": "ITEM_TROY_DISK", "expirationTimestampMs": "1472209767640", "deployerPlayerCodename": "Tangkwaas" } ] } 
 

-----------------------------------------------

**Comment by Ar1i** [comment]
not an error
