### ISSUE TITLE
Bot not loading/working

### ISSUE THREAD

**Issue by FredPassos92** [Ar1i/PokemonGo-Bot#3567]
I am getting this error for almost a day now. Sometimes happens for an hour or two. But it's taking too long now and I even download the new version today...

![error](https://cloud.githubusercontent.com/assets/20972593/18225791/15beb79e-71f4-11e6-93ec-c5cc8b80be3f.jpg)

**Comment by Jeremy2131** [comment]
@FredPassos92 something with the files

**Comment by FredPassos92** [comment]
Anything I can do to fix it?

**Comment by Jeremy2131** [comment]
@FredPassos92 try reinstall bot,check that you had all the files from the archive. And try start bot with windows compatibility,or i idk,sry :D

**Comment by MoMGeek** [comment]
I get this sometimes when I have the wrong login or password typed in.

**Comment by Jeremy2131** [comment]
@MoMGeek i dont think what he can do it :D

**Comment by FredPassos92** [comment]
Well I erased the bot and extrated a now one. Confirmed the PTC username and pw. Still get the same error

**Comment by nasierache** [comment]
try go to the builds only file...extract the latest update to the main files.. and let see what happen..

**Comment by Jeremy2131** [comment]
@FredPassos92 try use old version?

**Comment by FredPassos92** [comment]
@nasierache extract to the main folder?

**Comment by FredPassos92** [comment]
@Jeremy2131 gonna try it

**Comment by nasierache** [comment]
@FredPassos92 extract to where your bot files belong..

**Comment by FredPassos92** [comment]
Well none of those two worked :(

**Comment by Jeremy2131** [comment]
@nasierache first 4 folders must be with bot?

**Comment by FredPassos92** [comment]
This is my folder now

![sem titulo](https://cloud.githubusercontent.com/assets/20972593/18225982/3c3270a6-71f8-11e6-818f-51db09fd7b75.jpg)

**Comment by SscSPs** [comment]
go to builds only, extract the rar file, open the exe there

**Comment by FredPassos92** [comment]
It is what I have been doing since the last months xD

**Comment by SscSPs** [comment]
very well then, did you try different account?

**Comment by FredPassos92** [comment]
@SscSPs I did not. Gonna try it out

![sem titulo](https://cloud.githubusercontent.com/assets/20972593/18226023/21567e84-71f9-11e6-905a-510bff1e53d9.jpg)

**Comment by FredPassos92** [comment]
Didn't work with another account also

**Comment by nasierache** [comment]
make sure all this folder updated also
![untitled](https://cloud.githubusercontent.com/assets/21377477/18226070/c49a6c0a-7234-11e6-8063-4e12b858c75d.png)

**Comment by MTK4355** [comment]
I know you already said "confirmed PTC account" but are you sure you activated it? 

I got that message when I had forgotten to click the activation link after opening the account. It stops working after a couple of days if you don't activate it.

**Comment by FredPassos92** [comment]
How do I know if they are updated or not? Everytime a update comes out I delete all the files and extract the now ones

**Comment by FredPassos92** [comment]
@MTK4355 Yeah I did, and I can log in the acc in my smartphone

**Comment by SscSPs** [comment]
can you please translate this to English
![sketch](https://cloud.githubusercontent.com/assets/8400807/18226156/1dc7be7c-7221-11e6-8f23-0f934e171f37.png)

**Comment by FredPassos92** [comment]
Means "End of tracking pile of previous location where the exception was created"

**Comment by SscSPs** [comment]
so, does that mean the bot is not able to fetch pokestops?

**Comment by FredPassos92** [comment]
The bot doesnt even start. But he used to to everything.. fetch pokestops and pokemons

**Comment by SscSPs** [comment]
the GUI opens(the settings GUI)?

**Comment by FredPassos92** [comment]
Nop

**Comment by FredPassos92** [comment]
The setting yeah (GUI Edition) . But as soon as I press Start Bot the cmd window show up with those errors and the bot GUI doesnt show up

**Comment by FredPassos92** [comment]
![sem titulo](https://cloud.githubusercontent.com/assets/20972593/18226266/003abb7a-71fe-11e6-9695-16d197326089.jpg)

and then

![sem titulo2](https://cloud.githubusercontent.com/assets/20972593/18226274/1ab57e40-71fe-11e6-800e-bb5ab08f0e7c.jpg)

**Comment by SscSPs** [comment]
i will say that i have this problem too when I entered wrong password

I just downloaded it and deliberately entered wrong password just to check and this is the message i got:


[22:12:03] This bot is absolutely free and open-source!
[22:12:03] If you've paid for it. Request a chargeback immediately!
[22:12:03] Starting Execute on login server: Google
[22:12:03] Setting Pokemon Catch Count: to 0 for this session
[22:12:03] Setting Pokestop Farmed Count to 0 for this session
[22:12:03] Altidude was 0, resolved that. New Altidude is now: 10.0070150339724
[22:12:07] Error: Pokemon.Go.Rocket.API
[22:12:07] PokemonGo.RocketAPI.Exceptions.GoogleException: BadAuthentication
   at PokemonGo.RocketAPI.Login.GoogleLogin.<GetAccessToken>d__3.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Rpc\Login.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__18.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 101
[22:12:07] Trying to Restart.
[22:12:07] Restarting in 10 Seconds.

**Comment by SscSPs** [comment]
So i am going to say, Check your password.

**Comment by FredPassos92** [comment]
Well I tried my main acc and secondary acc on bot. Both get the error. Tried on my smartphone and both login without a problem..

**Comment by SscSPs** [comment]
The error is same... so that's why i suggested to try checking your password(may be there is some caps letters?)(i suggest trying again)**(and extract the bot in a different location to do a fresh start)**.
But anyhow, try changing your IP address

**Comment by FredPassos92** [comment]
Could my computer IP be banned?

**Comment by SscSPs** [comment]
can you paste the whole LOG after you press start?

**Comment by FredPassos92** [comment]
sure

![sem titulo](https://cloud.githubusercontent.com/assets/20972593/18226399/a9219900-7200-11e6-92c4-166e6a2371bf.jpg)

**Comment by FredPassos92** [comment]
It's working! I restarted my PC and usen hotspot shield
 But here is the thing. I'm using Spanish IP and botting on a Portuguese location. Could I get in trouble?

**Comment by SscSPs** [comment]
No, i dont think that if you get ban, this would be the reason.

**Comment by FredPassos92** [comment]
this would or wouldn't be? got confused now

**Comment by SscSPs** [comment]
it wouldn't be the reason you might get ban

**Comment by FredPassos92** [comment]
Well thank you all :)

**Comment by MTK4355** [comment]
This happened to me a few minutes ago. Not sure what the problem is yet, but my workaround looks like this:

Clear Username field and press tab key
Clear Password field and press tab key
Change authentication type and change back
Re-enter Username
Re-enter Password
Re-set all walk variables (because I haven't made them stick yet :P)
Start Bot

**Comment by vfallas97** [comment]
getting the error "we can't find any pokestops" how do i solve it?

**Comment by MTK4355** [comment]
More details please. Are you using a proxy IP? Are you running more than one instance of the bot?

**Comment by vfallas97** [comment]
more than one instance of the bot?

**Comment by vfallas97** [comment]
what is that?

**Comment by vfallas97** [comment]
and no, im not using a proxy ip or none of the things

**Comment by MTK4355** [comment]
Are you running more than one bot at a time on the same internet connection?

**Comment by Logxn** [comment]
Cant find pokestops is an IP ban.
I highly suggest using our Proxy funktion.

Remmeber: 1 bot per IP/Proxy

**Comment by vfallas97** [comment]
well i already got ip ban unban and still not working

**Comment by vfallas97** [comment]
how do i get a proxy?

**Comment by vfallas97** [comment]
im using a proxy that i get from the link the bot has and the thing gets stuck

**Comment by vfallas97** [comment]
im still getting the same error even using a proxy....

**Comment by MTK4355** [comment]
Use a different one. Some of those get banned too.

**Comment by vfallas97** [comment]
ok
