### ISSUE TITLE
-nogui exception

### ISSUE THREAD

**Issue by UnLMTD007** [Ar1i/PokemonGo-Bot#362]
build-only ver 30.07 00:34 and 30.07 13:10 same issue.

[14:16:54] You added -nogui! If you didnt setup correctly with the GUI. It wont work.

Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at PokemonGo.RocketAPI.Console.Program.Main(String[] args) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Console\Program.cs:line 108

**Comment by crack00r** [comment]
same here, nogui didnt work
