### ISSUE TITLE
Error on new build with translator

### ISSUE THREAD

**Issue by ocuellar** [Ar1i/PokemonGo-Bot#3899]
got this error with the new builds:

Seems like cannot translate correctly

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.MissingMethodException: Method not found: 'Void PokemonGo.RocketAPI.Logic.Translation.TranslationHandler.Init()'.
   at PokemonGo.RocketAPI.Console.GUI.GUI_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

![prtscr capture](https://cloud.githubusercontent.com/assets/20932696/18562308/620fe690-7b40-11e6-9c27-1fcd2c93fbab.jpg)

**Comment by suljo94** [comment]
Create a clean build,  set it up and the error will be gone

**Comment by ocuellar** [comment]
Thanks
