### ISSUE TITLE
Pokemon list Error

### ISSUE THREAD

**Issue by gothsk8er** [Ar1i/PokemonGo-Bot#4074]
[22:40:20] [PokemonList-Error]    at System.Windows.Forms.CheckedListBox.SetItemCheckState(Int32 index, CheckState value)
   at System.Windows.Forms.CheckedListBox.SetItemChecked(Int32 index, Boolean value)
   at PokemonGo.RocketAPI.Console.SniperPanel.Execute()
   at PokemonGo.RocketAPI.Console.Pokemons.<Execute>d__15.MoveNext()
[22:40:59] [PokemonList-Error]    at System.Windows.Forms.CheckedListBox.SetItemCheckState(Int32 index, CheckState value)
   at System.Windows.Forms.CheckedListBox.SetItemChecked(Int32 index, Boolean value)
   at PokemonGo.RocketAPI.Console.SniperPanel.Execute()
   at PokemonGo.RocketAPI.Console.Pokemons.<Execute>d__15.MoveNext()

How can i fix this ?

**Comment by mrevor1** [comment]
I'm having the same problem, and I'm sure we are not the only ones. Please tell how to fix this problem.
Thanks.

**Comment by Adj1e** [comment]
Me to, but if I ceck box like pict 1 bot runing well, but only show game simulator pokemon list gui is nothing

![11111111111111111](https://cloud.githubusercontent.com/assets/21359601/18812121/9d8e1d08-82f3-11e6-9583-f5b4df0ba77e.jpg)
![22222222222222](https://cloud.githubusercontent.com/assets/21359601/18812122/9d93c8c0-82f3-11e6-9e21-4b04fcca91b2.jpg)

**Comment by suljo94** [comment]
@MTK4355 was this the service that caused performance problems in pokelist?

**Comment by king2010116** [comment]
PICK2 CAN'T USE SPING

**Comment by Xelwon** [comment]
Hello. I need your screenshots of all  tabs from configuration window. To try resolve it. While.
In game simulator you can open rest of windows clicking in the pokeball.

**Comment by Xelwon** [comment]
Solved in last version

**Comment by Adj1e** [comment]
@Xelwon thanks bro
