### ISSUE TITLE
No multibot support

### ISSUE THREAD

**Issue by kingkong91108** [Ar1i/PokemonGo-Bot#509]
Is there a way to have a feature that makes it so we can run multiples of the bot at the same time? Because currently i can run them but due them logging the info or getting the same info from one place, they tend to boot each other off and gives errors saying 
[18:46:59] Exception: System.IO.IOException: The process cannot access the file 'C:\Users\King\Downloads\PokemonGo-Bot-master\PokemonGo-Bot-master\Builds Only\Latest Build - 31.7 01.44\Configs\LastCoords.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at PokemonGo.RocketAPI.Client.SaveLatLng(Double lat, Double lng)
   at PokemonGo.RocketAPI.Client.SetCoordinates(Double lat, Double lng, Double altitude)
   at PokemonGo.RocketAPI.Client.<UpdatePlayerLocation>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.Logic.Navigation.<HumanLikeWalking>d__4.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Navigation.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__17.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 384
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 138

**Comment by ElementV2** [comment]
I run 3 bot at the same time on 3 different account so its working :/

**Comment by 13XxM1CHA3lxX37** [comment]
Put them in seperate folders

**Comment by Ar1i** [comment]
^ this
