### ISSUE TITLE
Issue while connecting

### ISSUE THREAD

**Issue by abdellahaski** [Ar1i/PokemonGo-Bot#510]
Guys when I try to connect I get some errors here is the logs:

```
[01:56:40] Starting Execute on login server: Ptc
[01:56:42] To Activate Informations with Telegram, write the Bot a message for m
ore Informations
[01:56:43] Telegram Name: *********_bot
[01:56:43] [#0 of 25] retry request https://pgorelease.nianticlabs.com/plfe/rpc
- Error: System.Net.Http.HttpRequestException: An error occurred while sending t
he request. ---> System.Net.WebException: The underlying connection was closed:
An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to
 read data from the transport connection: An established connection was aborted
by the software in your host machine. ---> System.Net.Sockets.SocketException: A
n established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32
size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, In
t32 size, AsyncCallback callback, Object state)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at System.Net.TlsStream.EndRead(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext()
[01:56:43] [#0 of 25] retry request https://pgorelease.nianticlabs.com/plfe/rpc
- Error: System.Net.Http.HttpRequestException: An error occurred while sending t
he request. ---> System.Net.WebException: The underlying connection was closed:
An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to
 read data from the transport connection: An established connection was aborted
by the software in your host machine. ---> System.Net.Sockets.SocketException: A
n established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32
size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, In
t32 size, AsyncCallback callback, Object state)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at System.Net.TlsStream.EndRead(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext()

[01:56:44] Exception: Google.Protobuf.InvalidProtocolBufferException: SkipLastFi
eld called on an end-group tag, indicating that the corresponding start-group wa
s missing
   at Google.Protobuf.CodedInputStream.SkipLastField()
   at PokemonGo.RocketAPI.GeneratedCode.Response.MergeFrom(CodedInputStream inpu
t)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.Move
Next()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Client.<SetServer>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\U
sers\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Lo
gic.cs:line 128

[01:56:44] Starting again.. But waiting 10 Seconds..

[01:56:44] We got the API Url: pgorelease.nianticlabs.com/plfe/370

[01:56:51] We got the API Url: pgorelease.nianticlabs.com/plfe/370

[01:56:54] We got the API Url: pgorelease.nianticlabs.com/plfe/370

```

And It still repeating the same thing over and over

**Comment by squv** [comment]
same dude

**Comment by Ar1i** [comment]
Its cause ptc
