### ISSUE TITLE
there is something wrong：C:\Users\Ari\Desktop\PokemonGo Bot\Source\PokemonGo.RocketAPI.Logic\Logic.cs:line 128

### ISSUE THREAD

**Issue by MiaoMFoo** [Ar1i/PokemonGo-Bot#536]
[18:40:35] Exception: Google.Protobuf.InvalidProtocolBufferException: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
   at Google.Protobuf.CodedInputStream.SkipLastField()
   at PokemonGo.RocketAPI.GeneratedCode.Response.MergeFrom(CodedInputStream input)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext()
--- Throws an exception on a position at the end of the stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Client.<SetServer>d__29.MoveNext()
--- Throws an exception on a position at the end of the stack trace---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() position C:\Users\Ari\Desktop\PokemonGo Bot\Source\PokemonGo.RocketAPI.Logic\Logic.cs:line 128

**Comment by Ar1i** [comment]
Testing.. gimme some time to find that bug!

**Comment by Ar1i** [comment]
When does the error popup? Can you give me more informations?

**Comment by MiaoMFoo** [comment]
@Ar1i after updated the new version，it cannot be opened

**Comment by ShutUpPvP** [comment]
Tryed redownloading the file? Worked for me some patches ago

**Comment by MiaoMFoo** [comment]
@Ar1i it says： C:\Users\Ari.....
but i donnt have a user account “”Ari“” in my sysytem

**Comment by pokerave** [comment]
![error](https://cloud.githubusercontent.com/assets/20603254/17276124/c0ab616c-5727-11e6-8b5d-2e39147b95ff.jpg)
@Ar1i here's when it pops up

**Comment by MiaoMFoo** [comment]
@pokerave same as mine

**Comment by MiaoMFoo** [comment]
@Ar1i just 1

**Comment by MiaoMFoo** [comment]
@Ar1i I'd like to run more ，but no one can be running normal~

**Comment by pokerave** [comment]
I got 2 Bot. different folders.

**Comment by Ar1i** [comment]
After the error, does it restart new and works then?

**Comment by MiaoMFoo** [comment]
@Ar1i nope

**Comment by pokerave** [comment]
Mine does as you can see. it continues. :)

**Comment by MiaoMFoo** [comment]
continue after seconds，but as the same ，again and again

**Comment by MiaoMFoo** [comment]
https://github.com/PocketMobsters/PokeMobBot/issues/69
another bot ， looks like has the same bug~lol~

**Comment by MiaoMFoo** [comment]
byw. my system is win10
