### ISSUE TITLE
logic error or json 

### ISSUE THREAD

**Issue by simtechnos** [Ar1i/PokemonGo-Bot#626]
:10] Exception: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   at PokemonGo.RocketAPI.Logic.Utils.PokeVisionUtil.<GetNearPokemons>d__4.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Utils\PokeVisionUtil.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__16.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 369
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 138

**Comment by madpada** [comment]
What level is your guy?  I ran into this a lot when I started a bot on a level 1 guy... I THINK it might have something to do with some of the pokemon having ??? listed as the CP.  It would run just fine in spite of the error and eventually they disappeared.

**Comment by simtechnos** [comment]
its 24 level

**Comment by simtechnos** [comment]
![untitled](https://cloud.githubusercontent.com/assets/4362028/17278052/77f7ff5e-5770-11e6-83fa-4da0a902153f.png)
this is the whole thing.

**Comment by simtechnos** [comment]
i started facing this issue since the last update, before that it was all fine, is something missing on my system. i took a new notebook

**Comment by simtechnos** [comment]
started working automatically. thanks
