### ISSUE TITLE
Linux and MAC OS: App crashes with Google Login

### ISSUE THREAD

**Issue by amuessig** [Ar1i/PokemonGo-Bot#801]
When trying to login with Google, the app crashes on MAC OS and Linux with using WIne.

Should be the new Login
`[01:56:16] This bot is absolutely free and open-source!
[01:56:16] If you've paid for it. Request a chargeback immediately!
[01:56:16] Starting Execute on login server: Google
fixme:shell:URL_ParseUrl failed to parse L"GPSOAuthSharp"
[01:56:16] Error: mscorlib
[01:56:16] System.Security.Cryptography.CryptographicException: Unknown error "-2146893815".
   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.RSACryptoServiceProvider.EncryptKey(SafeKeyHandle pKeyContext, Byte[] pbKey, Int32 cbKey, Boolean fOAEP, ObjectHandleOnStack ohRetEncryptedKey)
   at System.Security.Cryptography.RSACryptoServiceProvider.Encrypt(Byte[] rgb, Boolean fOAEP)
   at DankMemes.GPSOAuthSharp.GoogleKeyUtils.CreateSignature(String email, String password, RSAParameters key)
   at DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformMasterLogin(String service, String deviceCountry, String operatorCountry, String lang, Int32 sdkVersion)
   at PokemonGo.RocketAPI.Login.GoogleLoginGPSOAuth.DoLogin(String username, String password) in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Login\GoogleLoginGPSOAuth.cs:line 19
   at PokemonGo.RocketAPI.Client.<DoGoogleLogin>d__25.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI\Client.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\Ari\Desktop\PokemonGo Bot\Github\PokemonGo-Bot\PokemonGo.RocketAPI.Logic\Logic.cs:line 56
[01:56:16] Trying to Restart.
[01:56:16] Restarting in 10 Seconds.`

It is working with a Pokemon Trainer Club account.
Thanks

**Comment by Ar1i** [comment]
Uhm, i dont have a mac.. so i cant test it..

**Comment by amuessig** [comment]
It's the same with Linux. I tried it on both operating systems.

**Comment by Ar1i** [comment]
Yeah, probably cause some packages are not supported in mono or wine?
